
on:
  push:
    branches: [ "main" ]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - run: git clone https://aur.archlinux.org/linux-mainline.git .
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    - name: Upload Package Archive
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
